/**
 * Tool Deal Finder - Data Model (v0)
 * fairValue = kit decomposition: bare tool + batteries (street value table) + charger + case.
 * Prices verified by browser on lastChecked date; staleHidden entries are NOT displayed.
 * Generated by gen_data.py — edit the catalog there, not here.
 */
const TOOL_DATA = {
  "lastUpdated": "2026-07-03T22:45:00Z",
  "retailers": {
    "homedepot": {
      "name": "The Home Depot"
    },
    "amazon": {
      "name": "Amazon"
    },
    "acmetools": {
      "name": "Acme Tools"
    },
    "lowes": {
      "name": "Lowe's"
    },
    "harborfreight": {
      "name": "Harbor Freight"
    }
  },
  "platforms": {
    "dewalt20v": "DeWalt 20V MAX",
    "m18": "Milwaukee M18",
    "m12": "Milwaukee M12",
    "makita18v": "Makita 18V LXT",
    "ryobi18v": "Ryobi 18V ONE+",
    "ridgid18v": "Ridgid 18V",
    "ego56v": "EGO 56V",
    "metabohpt36v": "Metabo HPT MultiVolt",
    "bauer20v": "Bauer 20V",
    "hercules20v": "Hercules 20V"
  },
  "batteryValueTable": {
    "dewalt20v|5.0": 119,
    "dewalt20v|4.0c": 99,
    "dewalt20v|2.0": 59,
    "m18|5.0": 109,
    "m18|2.0": 65,
    "m12|5.0": 89,
    "m12|2.0": 49,
    "makita18v|5.0": 119,
    "makita18v|2.0": 55,
    "ryobi18v|4.0": 69,
    "ryobi18v|2.0": 39,
    "ridgid18v|4.0": 79,
    "ego56v|5.0": 249,
    "ego56v|2.5": 149,
    "metabohpt36v|4.0": 99,
    "bauer20v|5.0": 45,
    "bauer20v|2.0": 18,
    "hercules20v|5.0": 70,
    "hercules20v|2.0": 35
  },
  "tools": [
    {
      "id": "dewalt-dcf850b",
      "brand": "DeWalt",
      "model": "DCF850B",
      "fullName": "DeWalt Atomic 20V Brushless 1/4in Impact Driver (Bare)",
      "platform": "dewalt20v",
      "platformName": "DeWalt 20V MAX",
      "toolType": "impact_driver",
      "config": {
        "bareToolValue": 140,
        "batteries": [],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 140,
      "specs": {
        "torque": "1825 in-lbs",
        "brushless": true,
        "weight": "2.0 lb"
      },
      "useCaseScores": {
        "diy": 8.4,
        "remodel": 9.0,
        "auto": 7.0,
        "electrical": 8.8,
        "yard": 0,
        "pro": 9.0
      },
      "modelNote": "",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "https://images.thdstatic.com/productImages/3fbaa197-52a0-45f1-b4dc-8a3a8e814a23/svn/dewalt-impact-drivers-dcf850b-64_600.jpg",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 129.0,
          "retailPrice": 169.0,
          "onSale": true,
          "inStock": true,
          "staleHidden": false,
          "lastChecked": "2026-07-03T22:45:00Z",
          "url": "https://www.homedepot.com/p/DEWALT-ATOMIC-20V-MAX-Cordless-Brushless-Compact-1-4-in-Impact-Driver-Tool-Only-DCF850B/316627328",
          "originalUrl": "https://www.homedepot.com/p/DEWALT-ATOMIC-20V-MAX-Cordless-Brushless-Compact-1-4-in-Impact-Driver-Tool-Only-DCF850B/316627328"
        }
      ],
      "priceHistory": [
        {
          "date": "2026-07-03",
          "price": 129.0
        }
      ]
    },
    {
      "id": "milwaukee-2953-20",
      "brand": "Milwaukee",
      "model": "2953-20",
      "fullName": "Milwaukee M18 FUEL 1/4in Hex Impact Driver (Bare)",
      "platform": "m18",
      "platformName": "Milwaukee M18",
      "toolType": "impact_driver",
      "config": {
        "bareToolValue": 155,
        "batteries": [],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 155,
      "specs": {
        "torque": "2000 in-lbs",
        "brushless": true,
        "weight": "2.4 lb"
      },
      "useCaseScores": {
        "diy": 8.0,
        "remodel": 9.2,
        "auto": 7.4,
        "electrical": 8.6,
        "yard": 0,
        "pro": 9.4
      },
      "modelNote": "",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "https://images.thdstatic.com/productImages/4b8d2df9-00a4-4068-b769-5d75368fd1cf/svn/milwaukee-impact-drivers-2953-20-64_600.jpg",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 179.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": true,
          "staleHidden": false,
          "lastChecked": "2026-07-03T22:45:00Z",
          "url": "https://www.homedepot.com/p/Milwaukee-M18-FUEL-18V-Lithium-Ion-Brushless-Cordless-1-4-in-Hex-Impact-Driver-Tool-Only-2953-20/320326875",
          "originalUrl": "https://www.homedepot.com/p/Milwaukee-M18-FUEL-18V-Lithium-Ion-Brushless-Cordless-1-4-in-Hex-Impact-Driver-Tool-Only-2953-20/320326875"
        }
      ],
      "priceHistory": [
        {
          "date": "2026-07-03",
          "price": 179.0
        }
      ]
    },
    {
      "id": "milwaukee-3697-22",
      "brand": "Milwaukee",
      "model": "3697-22",
      "fullName": "Milwaukee M18 FUEL 2-Tool Combo: Hammer Drill + Impact Driver (2x5.0Ah)",
      "platform": "m18",
      "platformName": "Milwaukee M18",
      "toolType": "combo_kit",
      "config": {
        "bareToolValue": 320,
        "batteries": [
          {
            "ah": "5.0",
            "qty": 2,
            "unitValue": 109
          }
        ],
        "chargerValue": 30,
        "caseValue": 20
      },
      "fairValue": 588,
      "specs": {
        "torque": "1400 in-lbs / 2000 in-lbs",
        "brushless": true
      },
      "useCaseScores": {
        "diy": 8.6,
        "remodel": 9.5,
        "auto": 7.8,
        "electrical": 8.4,
        "yard": 0,
        "pro": 9.6
      },
      "modelNote": "",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "https://images.thdstatic.com/productImages/53650d0a-9387-4588-adff-25e704ce7c7c/svn/milwaukee-power-tool-combo-kits-3697-22-64_600.jpg",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 349.0,
          "retailPrice": 399.0,
          "onSale": true,
          "inStock": true,
          "staleHidden": false,
          "lastChecked": "2026-07-03T22:45:00Z",
          "url": "https://www.homedepot.com/p/Milwaukee-M18-FUEL-18V-Lithium-Ion-Brushless-Cordless-Hammer-Drill-and-Impact-Driver-Combo-Kit-2-Tool-with-2-Batteries-3697-22/320326787",
          "originalUrl": "https://www.homedepot.com/p/Milwaukee-M18-FUEL-18V-Lithium-Ion-Brushless-Cordless-Hammer-Drill-and-Impact-Driver-Combo-Kit-2-Tool-with-2-Batteries-3697-22/320326787"
        }
      ],
      "priceHistory": [
        {
          "date": "2026-07-03",
          "price": 349.0
        }
      ]
    },
    {
      "id": "ryobi-psbdd02k2",
      "brand": "Ryobi",
      "model": "PSBDD02K2",
      "fullName": "Ryobi ONE+ HP Compact Brushless 1/2in Drill Kit (2 Batteries)",
      "platform": "ryobi18v",
      "platformName": "Ryobi 18V ONE+",
      "toolType": "drill",
      "config": {
        "bareToolValue": 95,
        "batteries": [
          {
            "ah": "2.0",
            "qty": 2,
            "unitValue": 39
          }
        ],
        "chargerValue": 20,
        "caseValue": 10
      },
      "fairValue": 203,
      "specs": {
        "torque": "400 in-lbs",
        "brushless": true,
        "weight": "2.4 lb"
      },
      "useCaseScores": {
        "diy": 9.2,
        "remodel": 7.2,
        "auto": 6.0,
        "electrical": 7.8,
        "yard": 0,
        "pro": 5.5
      },
      "modelNote": "",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "https://images.thdstatic.com/productImages/96d5c7bd-3d25-45b7-9ca3-7e93532548fa/svn/ryobi-power-drills-psbdd02k2-64_600.jpg",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 139.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": true,
          "staleHidden": false,
          "lastChecked": "2026-07-03T22:45:00Z",
          "url": "https://www.homedepot.com/p/RYOBI-ONE-HP-18V-Brushless-Cordless-Compact-1-2in-Drill-Driver-Kit-with-2-Compact-Batteries-and-Charger-PSBDD02K2/327697338",
          "originalUrl": "https://www.homedepot.com/p/RYOBI-ONE-HP-18V-Brushless-Cordless-Compact-1-2in-Drill-Driver-Kit-with-2-Compact-Batteries-and-Charger-PSBDD02K2/327697338"
        }
      ],
      "priceHistory": [
        {
          "date": "2026-07-03",
          "price": 139.0
        }
      ]
    },
    {
      "id": "makita-xfd131",
      "brand": "Makita",
      "model": "XFD131",
      "fullName": "Makita 18V LXT Brushless 1/2in Drill Kit (1x3.0Ah)",
      "platform": "makita18v",
      "platformName": "Makita 18V LXT",
      "toolType": "drill",
      "config": {
        "bareToolValue": 145,
        "batteries": [
          {
            "ah": "2.0",
            "qty": 1,
            "unitValue": 55
          }
        ],
        "chargerValue": 30,
        "caseValue": 15
      },
      "fairValue": 245,
      "specs": {
        "torque": "440 in-lbs",
        "brushless": true,
        "weight": "3.9 lb"
      },
      "useCaseScores": {
        "diy": 8.2,
        "remodel": 8.6,
        "auto": 6.2,
        "electrical": 7.6,
        "yard": 0,
        "pro": 8.6
      },
      "modelNote": "3.0Ah battery valued at 2.0 tier +$15",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "https://images.thdstatic.com/productImages/b6c06ffa-960a-4e93-b874-8a2d7985364d/svn/makita-power-drills-xfd131-64_600.jpg",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 179.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": true,
          "staleHidden": false,
          "lastChecked": "2026-07-03T22:45:00Z",
          "url": "https://www.homedepot.com/p/Makita-18V-LXT-Lithium-Ion-Brushless-Cordless-1-2-in-Driver-Drill-Kit-3-0Ah-XFD131/305926995",
          "originalUrl": "https://www.homedepot.com/p/Makita-18V-LXT-Lithium-Ion-Brushless-Cordless-1-2-in-Driver-Drill-Kit-3-0Ah-XFD131/305926995"
        }
      ],
      "priceHistory": [
        {
          "date": "2026-07-03",
          "price": 179.0
        }
      ]
    },
    {
      "id": "milwaukee-2962-20",
      "brand": "Milwaukee",
      "model": "2962-20",
      "fullName": "Milwaukee M18 FUEL 1/2in Mid-Torque Impact Wrench (Bare)",
      "platform": "m18",
      "platformName": "Milwaukee M18",
      "toolType": "impact_wrench",
      "config": {
        "bareToolValue": 250,
        "batteries": [],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 250,
      "specs": {
        "torque": "650 ft-lbs",
        "brushless": true,
        "weight": "5.1 lb"
      },
      "useCaseScores": {
        "diy": 5.5,
        "remodel": 6.0,
        "auto": 9.6,
        "electrical": 4.0,
        "yard": 0,
        "pro": 9.0
      },
      "modelNote": "",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "https://images.thdstatic.com/productImages/9c7469c9-6d06-4313-b8c6-dbf40e7ce75e/svn/milwaukee-impact-wrenches-2962-20-64_600.jpg",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 279.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": true,
          "staleHidden": false,
          "lastChecked": "2026-07-03T22:45:00Z",
          "url": "https://www.homedepot.com/p/Milwaukee-M18-FUEL-Gen-2-18V-Lithium-Ion-Brushless-Cordless-Mid-Torque-1-2-in-Impact-Wrench-w-Friction-Ring-Tool-Only-2962-20/313511878",
          "originalUrl": "https://www.homedepot.com/p/Milwaukee-M18-FUEL-Gen-2-18V-Lithium-Ion-Brushless-Cordless-Mid-Torque-1-2-in-Impact-Wrench-w-Friction-Ring-Tool-Only-2962-20/313511878"
        }
      ],
      "priceHistory": [
        {
          "date": "2026-07-03",
          "price": 279.0
        }
      ]
    },
    {
      "id": "ego-lm2135sp",
      "brand": "EGO",
      "model": "LM2135SP",
      "fullName": "EGO POWER+ 21in Self-Propelled Mower Kit (7.5Ah)",
      "platform": "ego56v",
      "platformName": "EGO 56V",
      "toolType": "mower",
      "config": {
        "bareToolValue": 280,
        "batteries": [
          {
            "ah": "5.0",
            "qty": 1,
            "unitValue": 249
          }
        ],
        "chargerValue": 60,
        "caseValue": 0
      },
      "fairValue": 589,
      "specs": {
        "runtime": "60 min",
        "selfPropelled": true
      },
      "useCaseScores": {
        "diy": 8.8,
        "remodel": 0,
        "auto": 0,
        "electrical": 0,
        "yard": 9.4,
        "pro": 6.5
      },
      "modelNote": "7.5Ah valued at 5.0 tier +$70",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "https://m.media-amazon.com/images/I/71+DP8NYPeL._AC_SX679_.jpg",
      "prices": [
        {
          "retailerId": "amazon",
          "currentPrice": 599.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": true,
          "staleHidden": false,
          "lastChecked": "2026-07-03T22:45:00Z",
          "url": "https://www.amazon.com/dp/B0857KWHHC?tag=tvschool-20",
          "originalUrl": "https://www.amazon.com/dp/B0857KWHHC?tag=tvschool-20"
        }
      ],
      "priceHistory": [
        {
          "date": "2026-07-03",
          "price": 599.0
        }
      ]
    },
    {
      "id": "ryobi-pbp005",
      "brand": "Ryobi",
      "model": "PBP005",
      "fullName": "Ryobi ONE+ 18V 4.0Ah Battery",
      "platform": "ryobi18v",
      "platformName": "Ryobi 18V ONE+",
      "toolType": "battery",
      "config": {
        "bareToolValue": 0,
        "batteries": [
          {
            "ah": "4.0",
            "qty": 1,
            "unitValue": 69
          }
        ],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 69,
      "specs": {},
      "useCaseScores": {
        "diy": 7.0,
        "remodel": 5.0,
        "auto": 5.0,
        "electrical": 5.0,
        "yard": 6.0,
        "pro": 4.0
      },
      "modelNote": "single battery at list; street value $69",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "https://images.thdstatic.com/productImages/b0b3568d-f440-45c3-b1ca-44c023241cb4/svn/ryobi-outdoor-power-batteries-chargers-pbp005-64_600.jpg",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 99.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": true,
          "staleHidden": false,
          "lastChecked": "2026-07-03T22:45:00Z",
          "url": "https://www.homedepot.com/p/RYOBI-ONE-18V-4-0-Ah-Lithium-Ion-Battery-PBP005/315039438",
          "originalUrl": "https://www.homedepot.com/p/RYOBI-ONE-18V-4-0-Ah-Lithium-Ion-Battery-PBP005/315039438"
        }
      ],
      "priceHistory": [
        {
          "date": "2026-07-03",
          "price": 99.0
        }
      ]
    },
    {
      "id": "dewalt-dcd800p1",
      "brand": "DeWalt",
      "model": "DCD800P1",
      "fullName": "DeWalt 20V MAX XR Brushless 1/2in Drill Kit (1x5.0Ah)",
      "platform": "dewalt20v",
      "platformName": "DeWalt 20V MAX",
      "toolType": "drill",
      "config": {
        "bareToolValue": 160,
        "batteries": [
          {
            "ah": "5.0",
            "qty": 1,
            "unitValue": 119
          }
        ],
        "chargerValue": 30,
        "caseValue": 15
      },
      "fairValue": 324,
      "specs": {
        "torque": "UWO 885",
        "brushless": true
      },
      "useCaseScores": {
        "diy": 8.4,
        "remodel": 9.0,
        "auto": 6.4,
        "electrical": 7.8,
        "yard": 0,
        "pro": 9.0
      },
      "modelNote": "OOS online 7/3; price recorded",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 243.03,
          "retailPrice": null,
          "onSale": false,
          "inStock": false,
          "staleHidden": true,
          "lastChecked": "",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": []
    },
    {
      "id": "milwaukee-48-11-1850",
      "brand": "Milwaukee",
      "model": "48-11-1850",
      "fullName": "Milwaukee M18 REDLITHIUM 5.0Ah Battery",
      "platform": "m18",
      "platformName": "Milwaukee M18",
      "toolType": "battery",
      "config": {
        "bareToolValue": 0,
        "batteries": [
          {
            "ah": "5.0",
            "qty": 1,
            "unitValue": 109
          }
        ],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 109,
      "specs": {},
      "useCaseScores": {
        "diy": 6.0,
        "remodel": 7.0,
        "auto": 7.0,
        "electrical": 6.0,
        "yard": 0,
        "pro": 8.0
      },
      "modelNote": "41% off list \u2014 anchor for M18 battery value",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "https://images.thdstatic.com/productImages/6c9940dc-2c35-4a5d-b5bb-b47a87a09ab5/svn/milwaukee-power-tool-batteries-48-11-1850-64_600.jpg",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 99.0,
          "retailPrice": 169.0,
          "onSale": true,
          "inStock": true,
          "staleHidden": false,
          "lastChecked": "2026-07-03T22:45:00Z",
          "url": "https://www.homedepot.com/p/Milwaukee-M18-18-Volt-5-0-Ah-Lithium-Ion-XC-Extended-Capacity-Battery-Pack-48-11-1850/205620421",
          "originalUrl": "https://www.homedepot.com/p/Milwaukee-M18-18-Volt-5-0-Ah-Lithium-Ion-XC-Extended-Capacity-Battery-Pack-48-11-1850/205620421"
        }
      ],
      "priceHistory": [
        {
          "date": "2026-07-03",
          "price": 99.0
        }
      ]
    },
    {
      "id": "milwaukee-48-11-2450",
      "brand": "Milwaukee",
      "model": "48-11-2450",
      "fullName": "Milwaukee M12 REDLITHIUM 5.0Ah Battery",
      "platform": "m12",
      "platformName": "Milwaukee M12",
      "toolType": "battery",
      "config": {
        "bareToolValue": 0,
        "batteries": [
          {
            "ah": "5.0",
            "qty": 1,
            "unitValue": 89
          }
        ],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 89,
      "specs": {},
      "useCaseScores": {
        "diy": 6.0,
        "remodel": 6.0,
        "auto": 7.5,
        "electrical": 7.5,
        "yard": 0,
        "pro": 7.0
      },
      "modelNote": "",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "https://images.thdstatic.com/productImages/9dd6affe-c9bc-4a32-a203-25b3ffb0e391/svn/milwaukee-power-tool-batteries-48-11-2450-64_600.jpg",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 99.0,
          "retailPrice": 129.0,
          "onSale": true,
          "inStock": true,
          "staleHidden": false,
          "lastChecked": "2026-07-03T22:45:00Z",
          "url": "https://www.homedepot.com/p/Milwaukee-M12-12-Volt-Lithium-Ion-XC-High-Output-5-0-Ah-Battery-Pack-48-11-2450/320268545",
          "originalUrl": "https://www.homedepot.com/p/Milwaukee-M12-12-Volt-Lithium-Ion-XC-High-Output-5-0-Ah-Battery-Pack-48-11-2450/320268545"
        }
      ],
      "priceHistory": [
        {
          "date": "2026-07-03",
          "price": 99.0
        }
      ]
    },
    {
      "id": "dewalt-dcb205",
      "brand": "DeWalt",
      "model": "DCB205",
      "fullName": "DeWalt 20V MAX 5.0Ah Battery",
      "platform": "dewalt20v",
      "platformName": "DeWalt 20V MAX",
      "toolType": "battery",
      "config": {
        "bareToolValue": 0,
        "batteries": [
          {
            "ah": "5.0",
            "qty": 1,
            "unitValue": 119
          }
        ],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 119,
      "specs": {},
      "useCaseScores": {
        "diy": 6.0,
        "remodel": 7.0,
        "auto": 6.0,
        "electrical": 6.0,
        "yard": 0,
        "pro": 8.0
      },
      "modelNote": "at list; wait for promo",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "https://images.thdstatic.com/productImages/da6fe409-aea7-4eb1-9ebe-974686a61b35/svn/dewalt-power-tool-batteries-dcb205-64_600.jpg",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 169.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": true,
          "staleHidden": false,
          "lastChecked": "2026-07-03T22:45:00Z",
          "url": "https://www.homedepot.com/p/DEWALT-20V-MAX-Premium-Lithium-Ion-5-0Ah-Battery-Pack-DCB205/205227130",
          "originalUrl": "https://www.homedepot.com/p/DEWALT-20V-MAX-Premium-Lithium-Ion-5-0Ah-Battery-Pack-DCB205/205227130"
        }
      ],
      "priceHistory": [
        {
          "date": "2026-07-03",
          "price": 169.0
        }
      ]
    },
    {
      "id": "makita-bl1850b",
      "brand": "Makita",
      "model": "BL1850B",
      "fullName": "Makita 18V LXT 5.0Ah Battery",
      "platform": "makita18v",
      "platformName": "Makita 18V LXT",
      "toolType": "battery",
      "config": {
        "bareToolValue": 0,
        "batteries": [
          {
            "ah": "5.0",
            "qty": 1,
            "unitValue": 119
          }
        ],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 119,
      "specs": {},
      "useCaseScores": {
        "diy": 6.0,
        "remodel": 7.0,
        "auto": 6.0,
        "electrical": 6.0,
        "yard": 0,
        "pro": 8.0
      },
      "modelNote": "at list",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "https://images.thdstatic.com/productImages/fcc08ee4-1397-4cc1-b22e-a03c84535db3/svn/makita-power-tool-batteries-bl1850b-64_600.jpg",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 169.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": true,
          "staleHidden": false,
          "lastChecked": "2026-07-03T22:45:00Z",
          "url": "https://www.homedepot.com/p/Makita-18V-LXT-Lithium-Ion-High-Capacity-Battery-Pack-5-0Ah-with-Fuel-Gauge-BL1850B/206607848",
          "originalUrl": "https://www.homedepot.com/p/Makita-18V-LXT-Lithium-Ion-High-Capacity-Battery-Pack-5-0Ah-with-Fuel-Gauge-BL1850B/206607848"
        }
      ],
      "priceHistory": [
        {
          "date": "2026-07-03",
          "price": 169.0
        }
      ]
    },
    {
      "id": "ego-ba2800t",
      "brand": "EGO",
      "model": "BA2800T",
      "fullName": "EGO 56V 5.0Ah Battery",
      "platform": "ego56v",
      "platformName": "EGO 56V",
      "toolType": "battery",
      "config": {
        "bareToolValue": 0,
        "batteries": [
          {
            "ah": "5.0",
            "qty": 1,
            "unitValue": 249
          }
        ],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 249,
      "specs": {},
      "useCaseScores": {
        "diy": 5.0,
        "remodel": 0,
        "auto": 0,
        "electrical": 0,
        "yard": 8.0,
        "pro": 6.0
      },
      "modelNote": "at list",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "https://m.media-amazon.com/images/I/61ApHxx7X2L._AC_SX679_.jpg",
      "prices": [
        {
          "retailerId": "amazon",
          "currentPrice": 299.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": true,
          "staleHidden": false,
          "lastChecked": "2026-07-03T22:45:00Z",
          "url": "https://www.amazon.com/dp/B07YKY61RF?tag=tvschool-20",
          "originalUrl": "https://www.amazon.com/dp/B07YKY61RF?tag=tvschool-20"
        }
      ],
      "priceHistory": [
        {
          "date": "2026-07-03",
          "price": 299.0
        }
      ]
    },
    {
      "id": "milwaukee-2904-20",
      "brand": "Milwaukee",
      "model": "2904-20",
      "fullName": "Milwaukee M18 FUEL 1/2in Hammer Drill (Bare)",
      "platform": "m18",
      "platformName": "Milwaukee M18",
      "toolType": "drill",
      "config": {
        "bareToolValue": 165,
        "batteries": [],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 165,
      "specs": {
        "torque": "1400 in-lbs",
        "brushless": true
      },
      "useCaseScores": {
        "diy": 7.8,
        "remodel": 9.4,
        "auto": 6.6,
        "electrical": 8.0,
        "yard": 0,
        "pro": 9.5
      },
      "modelNote": "",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 199.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": false,
          "staleHidden": true,
          "lastChecked": "",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": []
    },
    {
      "id": "dewalt-dcs573b",
      "brand": "DeWalt",
      "model": "DCS573B",
      "fullName": "DeWalt 20V MAX 7-1/4in Circular Saw FLEXVOLT Adv (Bare)",
      "platform": "dewalt20v",
      "platformName": "DeWalt 20V MAX",
      "toolType": "circular_saw",
      "config": {
        "bareToolValue": 165,
        "batteries": [],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 165,
      "specs": {
        "rpm": "5500",
        "brushless": true
      },
      "useCaseScores": {
        "diy": 7.6,
        "remodel": 9.2,
        "auto": 4.0,
        "electrical": 5.5,
        "yard": 0,
        "pro": 9.0
      },
      "modelNote": "",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 199.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": false,
          "staleHidden": true,
          "lastChecked": "",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": []
    },
    {
      "id": "milwaukee-2732-20",
      "brand": "Milwaukee",
      "model": "2732-20",
      "fullName": "Milwaukee M18 FUEL 7-1/4in Circular Saw (Bare)",
      "platform": "m18",
      "platformName": "Milwaukee M18",
      "toolType": "circular_saw",
      "config": {
        "bareToolValue": 180,
        "batteries": [],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 180,
      "specs": {
        "rpm": "5800",
        "brushless": true
      },
      "useCaseScores": {
        "diy": 7.4,
        "remodel": 9.3,
        "auto": 4.0,
        "electrical": 5.5,
        "yard": 0,
        "pro": 9.2
      },
      "modelNote": "",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 229.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": false,
          "staleHidden": true,
          "lastChecked": "",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": []
    },
    {
      "id": "dewalt-dcf891b",
      "brand": "DeWalt",
      "model": "DCF891B",
      "fullName": "DeWalt 20V MAX XR 1/2in Mid-Torque Impact Wrench (Bare)",
      "platform": "dewalt20v",
      "platformName": "DeWalt 20V MAX",
      "toolType": "impact_wrench",
      "config": {
        "bareToolValue": 230,
        "batteries": [],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 230,
      "specs": {
        "torque": "600 ft-lbs",
        "brushless": true
      },
      "useCaseScores": {
        "diy": 5.5,
        "remodel": 6.0,
        "auto": 9.4,
        "electrical": 4.0,
        "yard": 0,
        "pro": 8.8
      },
      "modelNote": "",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 249.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": false,
          "staleHidden": true,
          "lastChecked": "",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": []
    },
    {
      "id": "milwaukee-2554-20",
      "brand": "Milwaukee",
      "model": "2554-20",
      "fullName": "Milwaukee M12 FUEL 3/8in Stubby Impact Wrench (Bare)",
      "platform": "m12",
      "platformName": "Milwaukee M12",
      "toolType": "impact_wrench",
      "config": {
        "bareToolValue": 155,
        "batteries": [],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 155,
      "specs": {
        "torque": "250 ft-lbs",
        "brushless": true,
        "length": "4.8 in"
      },
      "useCaseScores": {
        "diy": 5.0,
        "remodel": 5.5,
        "auto": 9.7,
        "electrical": 6.0,
        "yard": 0,
        "pro": 8.0
      },
      "modelNote": "",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 179.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": false,
          "staleHidden": true,
          "lastChecked": "",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": []
    },
    {
      "id": "milwaukee-2447-20",
      "brand": "Milwaukee",
      "model": "2447-20",
      "fullName": "Milwaukee M12 3/8in Crown Stapler (Bare)",
      "platform": "m12",
      "platformName": "Milwaukee M12",
      "toolType": "specialty",
      "config": {
        "bareToolValue": 85,
        "batteries": [],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 85,
      "specs": {},
      "useCaseScores": {
        "diy": 6.5,
        "remodel": 7.5,
        "auto": 3.0,
        "electrical": 6.0,
        "yard": 0,
        "pro": 6.0
      },
      "modelNote": "",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 99.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": false,
          "staleHidden": true,
          "lastChecked": "",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": []
    },
    {
      "id": "makita-xgt-gph01d",
      "brand": "Makita",
      "model": "GPH01D",
      "fullName": "Makita 40V XGT Brushless Hammer Drill Kit (2.5Ah)",
      "platform": "makita18v",
      "platformName": "Makita 18V LXT",
      "toolType": "drill",
      "config": {
        "bareToolValue": 230,
        "batteries": [
          {
            "ah": "2.0",
            "qty": 1,
            "unitValue": 55
          }
        ],
        "chargerValue": 30,
        "caseValue": 15
      },
      "fairValue": 330,
      "specs": {
        "torque": "1250 in-lbs",
        "brushless": true
      },
      "useCaseScores": {
        "diy": 7.0,
        "remodel": 9.0,
        "auto": 6.0,
        "electrical": 7.0,
        "yard": 0,
        "pro": 9.3
      },
      "modelNote": "XGT valued on 18V table v0 \u2014 refine",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 329.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": false,
          "staleHidden": true,
          "lastChecked": "",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": []
    },
    {
      "id": "ryobi-p1819",
      "brand": "Ryobi",
      "model": "P1819",
      "fullName": "Ryobi ONE+ 18V 6-Tool Combo Kit",
      "platform": "ryobi18v",
      "platformName": "Ryobi 18V ONE+",
      "toolType": "combo_kit",
      "config": {
        "bareToolValue": 280,
        "batteries": [
          {
            "ah": "4.0",
            "qty": 1,
            "unitValue": 69
          },
          {
            "ah": "2.0",
            "qty": 1,
            "unitValue": 39
          }
        ],
        "chargerValue": 20,
        "caseValue": 20
      },
      "fairValue": 428,
      "specs": {},
      "useCaseScores": {
        "diy": 9.4,
        "remodel": 7.0,
        "auto": 5.5,
        "electrical": 6.5,
        "yard": 3.0,
        "pro": 4.5
      },
      "modelNote": "",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 399.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": false,
          "staleHidden": true,
          "lastChecked": "",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": []
    },
    {
      "id": "ridgid-r9208",
      "brand": "Ridgid",
      "model": "R9208",
      "fullName": "Ridgid 18V 2-Tool Combo: Drill + Impact (2x2.0Ah)",
      "platform": "ridgid18v",
      "platformName": "Ridgid 18V",
      "toolType": "combo_kit",
      "config": {
        "bareToolValue": 190,
        "batteries": [
          {
            "ah": "4.0",
            "qty": 1,
            "unitValue": 79
          }
        ],
        "chargerValue": 25,
        "caseValue": 15
      },
      "fairValue": 309,
      "specs": {
        "brushless": true
      },
      "useCaseScores": {
        "diy": 8.6,
        "remodel": 8.0,
        "auto": 6.0,
        "electrical": 7.0,
        "yard": 0,
        "pro": 7.5
      },
      "modelNote": "LSA warranty adds value not modeled in v0",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 249.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": false,
          "staleHidden": true,
          "lastChecked": "",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": []
    },
    {
      "id": "ego-st1511t",
      "brand": "EGO",
      "model": "ST1511T",
      "fullName": "EGO POWER+ 15in String Trimmer Kit (2.5Ah)",
      "platform": "ego56v",
      "platformName": "EGO 56V",
      "toolType": "trimmer",
      "config": {
        "bareToolValue": 180,
        "batteries": [
          {
            "ah": "2.5",
            "qty": 1,
            "unitValue": 149
          }
        ],
        "chargerValue": 60,
        "caseValue": 0
      },
      "fairValue": 389,
      "specs": {
        "runtime": "45 min"
      },
      "useCaseScores": {
        "diy": 8.6,
        "remodel": 0,
        "auto": 0,
        "electrical": 0,
        "yard": 9.0,
        "pro": 6.0
      },
      "modelNote": "",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "amazon",
          "currentPrice": 229.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": false,
          "staleHidden": true,
          "lastChecked": "",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": []
    },
    {
      "id": "ego-lb6151",
      "brand": "EGO",
      "model": "LB6151",
      "fullName": "EGO POWER+ 615 CFM Blower Kit (2.5Ah)",
      "platform": "ego56v",
      "platformName": "EGO 56V",
      "toolType": "blower",
      "config": {
        "bareToolValue": 190,
        "batteries": [
          {
            "ah": "2.5",
            "qty": 1,
            "unitValue": 149
          }
        ],
        "chargerValue": 60,
        "caseValue": 0
      },
      "fairValue": 399,
      "specs": {
        "cfm": "615"
      },
      "useCaseScores": {
        "diy": 8.4,
        "remodel": 0,
        "auto": 0,
        "electrical": 0,
        "yard": 9.2,
        "pro": 6.5
      },
      "modelNote": "",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "amazon",
          "currentPrice": 229.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": false,
          "staleHidden": true,
          "lastChecked": "",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": []
    },
    {
      "id": "metabohpt-wh36dbdl2",
      "brand": "Metabo HPT",
      "model": "WH36DB",
      "fullName": "Metabo HPT MultiVolt 36V Triple Hammer Impact Driver (Bare)",
      "platform": "metabohpt36v",
      "platformName": "Metabo HPT MultiVolt",
      "toolType": "impact_driver",
      "config": {
        "bareToolValue": 150,
        "batteries": [],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 150,
      "specs": {
        "torque": "1832 in-lbs",
        "brushless": true
      },
      "useCaseScores": {
        "diy": 7.0,
        "remodel": 8.8,
        "auto": 6.5,
        "electrical": 7.5,
        "yard": 0,
        "pro": 8.8
      },
      "modelNote": "",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "amazon",
          "currentPrice": 159.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": false,
          "staleHidden": true,
          "lastChecked": "",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": []
    },
    {
      "id": "dewalt-dcs367b",
      "brand": "DeWalt",
      "model": "DCS367B",
      "fullName": "DeWalt 20V MAX XR Compact Recip Saw (Bare)",
      "platform": "dewalt20v",
      "platformName": "DeWalt 20V MAX",
      "toolType": "recip_saw",
      "config": {
        "bareToolValue": 150,
        "batteries": [],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 150,
      "specs": {
        "brushless": true,
        "spm": "2900"
      },
      "useCaseScores": {
        "diy": 7.2,
        "remodel": 8.8,
        "auto": 6.0,
        "electrical": 7.8,
        "yard": 5.0,
        "pro": 8.6
      },
      "modelNote": "",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 179.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": false,
          "staleHidden": true,
          "lastChecked": "",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": []
    },
    {
      "id": "milwaukee-2821-20",
      "brand": "Milwaukee",
      "model": "2821-20",
      "fullName": "Milwaukee M18 FUEL SAWZALL Recip Saw (Bare)",
      "platform": "m18",
      "platformName": "Milwaukee M18",
      "toolType": "recip_saw",
      "config": {
        "bareToolValue": 180,
        "batteries": [],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 180,
      "specs": {
        "brushless": true,
        "spm": "3000"
      },
      "useCaseScores": {
        "diy": 7.0,
        "remodel": 9.0,
        "auto": 6.2,
        "electrical": 7.8,
        "yard": 5.0,
        "pro": 9.2
      },
      "modelNote": "",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 229.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": false,
          "staleHidden": true,
          "lastChecked": "",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": []
    },
    {
      "id": "ryobi-p423",
      "brand": "Ryobi",
      "model": "P423",
      "fullName": "Ryobi ONE+ 18V Brushless 4-1/2in Angle Grinder (Bare)",
      "platform": "ryobi18v",
      "platformName": "Ryobi 18V ONE+",
      "toolType": "grinder",
      "config": {
        "bareToolValue": 75,
        "batteries": [],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 75,
      "specs": {
        "rpm": "10400",
        "brushless": true
      },
      "useCaseScores": {
        "diy": 8.0,
        "remodel": 6.8,
        "auto": 7.0,
        "electrical": 5.0,
        "yard": 0,
        "pro": 5.0
      },
      "modelNote": "",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 89.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": false,
          "staleHidden": true,
          "lastChecked": "",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": []
    },
    {
      "id": "makita-xag04z",
      "brand": "Makita",
      "model": "XAG04Z",
      "fullName": "Makita 18V LXT Brushless 4-1/2in Grinder (Bare)",
      "platform": "makita18v",
      "platformName": "Makita 18V LXT",
      "toolType": "grinder",
      "config": {
        "bareToolValue": 130,
        "batteries": [],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 130,
      "specs": {
        "rpm": "8500",
        "brushless": true
      },
      "useCaseScores": {
        "diy": 6.5,
        "remodel": 7.5,
        "auto": 7.5,
        "electrical": 5.0,
        "yard": 0,
        "pro": 8.8
      },
      "modelNote": "",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "homedepot",
          "currentPrice": 149.0,
          "retailPrice": null,
          "onSale": false,
          "inStock": false,
          "staleHidden": true,
          "lastChecked": "",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": []
    },
    {
      "id": "bauer-3sp-iw",
      "brand": "Bauer",
      "model": "BAUER-3SIW",
      "fullName": "Bauer 20V Brushless 1/2in 3-Speed Impact Wrench (Tool Only)",
      "platform": "bauer20v",
      "platformName": "Bauer 20V",
      "toolType": "impact_wrench",
      "config": {
        "bareToolValue": 50,
        "batteries": [],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 50,
      "specs": {
        "torque": "450 ft-lbs",
        "brushless": true
      },
      "useCaseScores": {
        "diy": 5.5,
        "remodel": 6.0,
        "auto": 8.8,
        "electrical": 4.0,
        "yard": 0,
        "pro": 6.5
      },
      "modelNote": "HF item# TBD; price verified 2026-07-05",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "harborfreight",
          "currentPrice": 49.99,
          "retailPrice": null,
          "onSale": false,
          "inStock": true,
          "staleHidden": false,
          "lastChecked": "2026-07-03T22:45:00Z",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": [
        {
          "date": "2026-07-03",
          "price": 49.99
        }
      ]
    },
    {
      "id": "bauer-ht-iw",
      "brand": "Bauer",
      "model": "BAUER-HTIW",
      "fullName": "Bauer 20V Brushless 1/2in High-Torque Impact Wrench Kit (5.0Ah)",
      "platform": "bauer20v",
      "platformName": "Bauer 20V",
      "toolType": "impact_wrench",
      "config": {
        "bareToolValue": 100,
        "batteries": [
          {
            "ah": "5.0",
            "qty": 1,
            "unitValue": 45
          }
        ],
        "chargerValue": 10,
        "caseValue": 0
      },
      "fairValue": 155,
      "specs": {
        "torque": "1200 ft-lbs",
        "brushless": true
      },
      "useCaseScores": {
        "diy": 5.5,
        "remodel": 6.0,
        "auto": 9.0,
        "electrical": 4.0,
        "yard": 0,
        "pro": 7.0
      },
      "modelNote": "kit w/ 5.0Ah+charger; HF item# TBD; verified 2026-07-05",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "harborfreight",
          "currentPrice": 159.99,
          "retailPrice": null,
          "onSale": false,
          "inStock": true,
          "staleHidden": false,
          "lastChecked": "2026-07-03T22:45:00Z",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": [
        {
          "date": "2026-07-03",
          "price": 159.99
        }
      ]
    },
    {
      "id": "bauer-drill",
      "brand": "Bauer",
      "model": "BAUER-DD12",
      "fullName": "Bauer 20V Cordless 1/2in Drill/Driver Kit (2.0Ah)",
      "platform": "bauer20v",
      "platformName": "Bauer 20V",
      "toolType": "drill",
      "config": {
        "bareToolValue": 32,
        "batteries": [
          {
            "ah": "2.0",
            "qty": 1,
            "unitValue": 18
          }
        ],
        "chargerValue": 10,
        "caseValue": 0
      },
      "fairValue": 60,
      "specs": {
        "brushless": false
      },
      "useCaseScores": {
        "diy": 7.5,
        "remodel": 6.0,
        "auto": 4.0,
        "electrical": 6.0,
        "yard": 0,
        "pro": 4.5
      },
      "modelNote": "non-brushless kit; HF item# TBD; verified 2026-07-05",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "harborfreight",
          "currentPrice": 54.99,
          "retailPrice": null,
          "onSale": false,
          "inStock": true,
          "staleHidden": false,
          "lastChecked": "2026-07-03T22:45:00Z",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": [
        {
          "date": "2026-07-03",
          "price": 54.99
        }
      ]
    },
    {
      "id": "bauer-blower",
      "brand": "Bauer",
      "model": "BAUER-JFB",
      "fullName": "Bauer 20V Cordless 96 MPH Jet Fan Blower Kit (5.0Ah)",
      "platform": "bauer20v",
      "platformName": "Bauer 20V",
      "toolType": "blower",
      "config": {
        "bareToolValue": 45,
        "batteries": [
          {
            "ah": "5.0",
            "qty": 1,
            "unitValue": 45
          }
        ],
        "chargerValue": 10,
        "caseValue": 0
      },
      "fairValue": 100,
      "specs": {
        "cfm": "338"
      },
      "useCaseScores": {
        "diy": 7.0,
        "remodel": 0,
        "auto": 0,
        "electrical": 0,
        "yard": 8.5,
        "pro": 5.0
      },
      "modelNote": "kit; HF item# TBD; verified 2026-07-05",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "harborfreight",
          "currentPrice": 99.99,
          "retailPrice": null,
          "onSale": false,
          "inStock": true,
          "staleHidden": false,
          "lastChecked": "2026-07-03T22:45:00Z",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": [
        {
          "date": "2026-07-03",
          "price": 99.99
        }
      ]
    },
    {
      "id": "hercules-compact-iw",
      "brand": "Hercules",
      "model": "HERC-CIW",
      "fullName": "Hercules 20V Brushless 1/2in Compact 4-Mode Impact Wrench (Tool Only)",
      "platform": "hercules20v",
      "platformName": "Hercules 20V",
      "toolType": "impact_wrench",
      "config": {
        "bareToolValue": 70,
        "batteries": [],
        "chargerValue": 0,
        "caseValue": 0
      },
      "fairValue": 70,
      "specs": {
        "torque": "330 ft-lbs",
        "brushless": true
      },
      "useCaseScores": {
        "diy": 6.0,
        "remodel": 6.5,
        "auto": 9.0,
        "electrical": 5.0,
        "yard": 0,
        "pro": 7.5
      },
      "modelNote": "HF item# TBD; price verified 2026-07-05",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "harborfreight",
          "currentPrice": 69.99,
          "retailPrice": null,
          "onSale": false,
          "inStock": true,
          "staleHidden": false,
          "lastChecked": "2026-07-03T22:45:00Z",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": [
        {
          "date": "2026-07-03",
          "price": 69.99
        }
      ]
    },
    {
      "id": "hercules-ultra-iw",
      "brand": "Hercules",
      "model": "HERC-UTIW",
      "fullName": "Hercules 20V Brushless 1/2in Ultra-Torque Impact Wrench Kit (5.0Ah)",
      "platform": "hercules20v",
      "platformName": "Hercules 20V",
      "toolType": "impact_wrench",
      "config": {
        "bareToolValue": 150,
        "batteries": [
          {
            "ah": "5.0",
            "qty": 1,
            "unitValue": 70
          }
        ],
        "chargerValue": 20,
        "caseValue": 0
      },
      "fairValue": 240,
      "specs": {
        "torque": "1100 ft-lbs",
        "brushless": true
      },
      "useCaseScores": {
        "diy": 5.5,
        "remodel": 6.0,
        "auto": 9.3,
        "electrical": 4.0,
        "yard": 0,
        "pro": 8.5
      },
      "modelNote": "kit w/ 5.0Ah+charger; HF item# TBD; verified 2026-07-05",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "harborfreight",
          "currentPrice": 249.99,
          "retailPrice": null,
          "onSale": false,
          "inStock": true,
          "staleHidden": false,
          "lastChecked": "2026-07-03T22:45:00Z",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": [
        {
          "date": "2026-07-03",
          "price": 249.99
        }
      ]
    },
    {
      "id": "hercules-impact-driver",
      "brand": "Hercules",
      "model": "HERC-CID",
      "fullName": "Hercules 20V Brushless 1/4in Compact 3-Speed Impact Driver Kit (2.0Ah)",
      "platform": "hercules20v",
      "platformName": "Hercules 20V",
      "toolType": "impact_driver",
      "config": {
        "bareToolValue": 52,
        "batteries": [
          {
            "ah": "2.0",
            "qty": 1,
            "unitValue": 35
          }
        ],
        "chargerValue": 20,
        "caseValue": 0
      },
      "fairValue": 107,
      "specs": {
        "torque": "1900 in-lbs",
        "brushless": true
      },
      "useCaseScores": {
        "diy": 8.0,
        "remodel": 8.5,
        "auto": 7.0,
        "electrical": 8.0,
        "yard": 0,
        "pro": 8.5
      },
      "modelNote": "kit w/ 2.0Ah+charger; HF item# TBD; verified 2026-07-05",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "harborfreight",
          "currentPrice": 97.99,
          "retailPrice": null,
          "onSale": false,
          "inStock": true,
          "staleHidden": false,
          "lastChecked": "2026-07-03T22:45:00Z",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": [
        {
          "date": "2026-07-03",
          "price": 97.99
        }
      ]
    },
    {
      "id": "hercules-drill",
      "brand": "Hercules",
      "model": "HERC-DD12",
      "fullName": "Hercules 20V Brushless 1/2in Drill/Driver Kit w/ Side Handle (2.0Ah)",
      "platform": "hercules20v",
      "platformName": "Hercules 20V",
      "toolType": "drill",
      "config": {
        "bareToolValue": 55,
        "batteries": [
          {
            "ah": "2.0",
            "qty": 1,
            "unitValue": 35
          }
        ],
        "chargerValue": 20,
        "caseValue": 0
      },
      "fairValue": 110,
      "specs": {
        "torque": "600 in-lbs",
        "brushless": true
      },
      "useCaseScores": {
        "diy": 8.2,
        "remodel": 8.4,
        "auto": 6.0,
        "electrical": 7.5,
        "yard": 0,
        "pro": 8.5
      },
      "modelNote": "kit w/ 2.0Ah+charger; HF item# TBD; verified 2026-07-05",
      "valueModel": "v0-decomposition-2026-07-03",
      "image": "",
      "prices": [
        {
          "retailerId": "harborfreight",
          "currentPrice": 97.99,
          "retailPrice": null,
          "onSale": false,
          "inStock": true,
          "staleHidden": false,
          "lastChecked": "2026-07-03T22:45:00Z",
          "url": "",
          "originalUrl": ""
        }
      ],
      "priceHistory": [
        {
          "date": "2026-07-03",
          "price": 97.99
        }
      ]
    }
  ]
};
